include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_single_quotes: true
    directives_ordering: true
    unawaited_futures: true

analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**
