name: moneyquest
description: MoneyQuest starter app (Flutter)
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^16.1.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.68.0
  uuid: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/airi/
